import type { NicheCatalog, Offer, Product } from "@/config/product-types";

const img = (folder: string, file: string) =>
  `/images/products/watches/${folder}/${file}`;

const products: Product[] = [
  {
    id: "armani-chrono",
    slug: "chrono-elegance",
    nameAr: "ساعة VORLAY كرونوغراف أنيقة",
    nameEn: "VORLAY Chronograph Elegance",
    headline: "كرونوغراف أنيق كيبان غالي من أول نظرة",
    subheading:
      "ساعة رجالية كرونوغراف بمعدن أنيق — مناسبة للخدمة والطلعات والهدية. الدفع عند الاستلام فكل المغرب.",
    cardHeading: "ستايل يومي أنيق",
    cardSubheading: "للمكتب، الهدية، والطلعات",
    bestFor: ["الطلعات", "الهدية للرجال", "الستايل اليومي"],
    benefits: [
      "تصميم كرونوغراف كيبان فاخر فالتصاور.",
      "سوار معدن ثابت ومناسب للاستعمال اليومي.",
      "تعبئة هدية سهلة — لوك مرتب من أول فتح.",
      "الدفع عند الاستلام وتأكيد الطلب بالهاتف.",
    ],
    pains: [
      "بغيت ساعة كيبان فيها الستايل بلا ما تدفع ثمن المحلات الغالية؟",
      "كتقلّب على هدية رجالية زوينة وما كتعرفش شنو تختار؟",
      "خاصك ساعة تليق مع الجينز ومع اللبسة الرسمية؟",
    ],
    painResponses: [
      "هاد الكرونوغراف كيعطي حضور قوي فالمعاصم بثمن مناسب للمغرب.",
      "اختيار واضح للهدية — شكل أنيق وكيتفتح بثقة.",
      "ستايل محايد: يمشي مع الخدمة ومع الطلعات.",
    ],
    mechanism:
      "ساعة فاشن رجالية كرونوغراف من VORLAY — للاستعمال اليومي والهدية، بتجربة طلب واضحة والدفع عند الاستلام.",
    eyebrow: "VORLAY Watches · كرونوغراف رجالي · الدفع عند الاستلام",
    image: img("armani", "armani-hero.jpg"),
    heroImageFit: "contain",
    carouselImageFit: "contain",
    images: [
      img("armani", "armani-hero.jpg"),
      img("armani", "armani-blue-box.jpg"),
      img("armani", "armani-02.jpg"),
      img("armani", "armani-04.jpg"),
    ],
    afterPainImage: img("armani", "armani-blue-box.jpg"),
    storyImages: [img("armani", "armani-blue-box.jpg"), img("armani", "armani-04.jpg")],
    crossSellIds: ["gshock", "benyar"],
    offers: [
      {
        id: "armani-1",
        productId: "armani-chrono",
        quantity: 1,
        title: "ساعة واحدة",
        subtitle: "الأكثر طلباً للرجال",
        badge: "الأكثر اختياراً",
        priceMad: 349,
        compareAtPriceMad: 499,
        recommended: true,
      },
      {
        id: "armani-2",
        productId: "armani-chrono",
        quantity: 2,
        title: "ساعتين",
        subtitle: "واحدة ليك وواحدة هدية",
        badge: "وفّر أكثر",
        priceMad: 649,
        compareAtPriceMad: 698,
      },
    ],
  },
  {
    id: "gshock",
    slug: "sport-watch",
    nameAr: "ساعة VORLAY رياضية",
    nameEn: "VORLAY Sport Watch",
    headline: "رياضية قوية — للرجال اللي كيبغيو يتحركو",
    subheading:
      "ساعة رجالية بستايل رياضي: حضور كبير، مريحة للحركة اليومية، وألوان كتشد العين. مثالية للخدمة والسبور.",
    cardHeading: "ستايل رياضي يومي",
    cardSubheading: "للشباب، السبور، والاستعمال القاسي",
    bestFor: ["الرياضة", "الشباب", "الاستعمال اليومي"],
    benefits: [
      "شكل رياضي قوي وكيبان واضح فالمعاصم.",
      "سوار مريح للاستعمال الطويل.",
      "ثمن مناسب باش تجرب البراند بلا مخاطرة.",
      "توصيل + الدفع عند الاستلام.",
    ],
    pains: [
      "الساعات الرقيقة كتهرس ليك بسرعة؟",
      "بغيت ساعة رجالية كتبان قوية فالتصاور؟",
      "كتقلب على ساعة يومية ما تتعبّكش فالثمن؟",
    ],
    painResponses: [
      "الستايل الرياضي كيعطي قوة وحضور — مناسب للحركة اليومية.",
      "التصميم الكبير كيبان واضح فالإعلانات والمعاصم.",
      "ثمن دخول مريح مع نفس تجربة الطلب ديال VORLAY.",
    ],
    mechanism:
      "ساعة فاشن رجالية بستايل رياضي من VORLAY — مطلوبة للرجال فالمغرب، مع الدفع عند الاستلام.",
    eyebrow: "VORLAY Watches · ستايل رياضي · الدفع عند الاستلام",
    image: img("gshock", "gshock-01.jpg"),
    heroImageFit: "contain",
    carouselImageFit: "contain",
    images: [
      img("gshock", "gshock-01.jpg"),
      img("gshock", "gshock-02.jpg"),
      img("gshock", "gshock-03.jpg"),
      img("gshock", "gshock-04.jpg"),
      img("gshock", "gshock-05.jpg"),
      img("gshock", "gshock-06.jpg"),
    ],
    afterPainImage: img("gshock", "gshock-03.jpg"),
    storyImages: [img("gshock", "gshock-04.jpg"), img("gshock", "gshock-05.jpg")],
    crossSellIds: ["armani-chrono", "benyar"],
    offers: [
      {
        id: "gshock-1",
        productId: "gshock",
        quantity: 1,
        title: "ساعة واحدة",
        subtitle: "دخول سهل للستايل الرياضي",
        badge: "الأكثر مبيعاً",
        priceMad: 279,
        compareAtPriceMad: 399,
        recommended: true,
      },
      {
        id: "gshock-2",
        productId: "gshock",
        quantity: 2,
        title: "ساعتين",
        subtitle: "وفّر على جوج",
        badge: "عرض ثنائي",
        priceMad: 499,
        compareAtPriceMad: 558,
      },
    ],
  },
  {
    id: "benyar",
    slug: "chrono-pro",
    nameAr: "ساعة VORLAY كرونوغراف Pro",
    nameEn: "VORLAY Chronograph Pro",
    headline: "كرونوغراف رجالي بوزن وحضور",
    subheading:
      "كرونوغراف رجالي بحضور قوي: معدن، لوك كيبان أغلى من الثمن، وخيار واضح للهدية.",
    cardHeading: "لوك قوي بثمن ذكي",
    cardSubheading: "للرجال اللي كيبغيو ساعة كتفرض وجودها",
    bestFor: ["الهدية", "الستايل الرسمي", "الطلعات المسائية"],
    benefits: [
      "كرونوغراف بثلاثة عيون كيعطي شكل فاخر.",
      "سوار معدن بوزن محسوس فاليد.",
      "مثالية كهدية رجالية واضحة.",
      "طلب بسيط: اسم، تليفون، مدينة — والدفع فالدار.",
    ],
    pains: [
      "الساعات الرخيصة كيبانو رخاص فالتصاور؟",
      "بغيت هدية رجالية ما تكونش تافهة؟",
      "كتقلب على لوك قوي بلا ما تدخل فثمن 1500 درهم؟",
    ],
    painResponses: [
      "التصميم والكرونوغراف كيعطيو حضور قوي فالمعاصم والفيديوهات.",
      "هدية واضحة: ساعة كبيرة، معدن، وشكل مرتب.",
      "ثمن متوسط بين Avito الرخيص ومواقع الـ 1500 درهم.",
    ],
    mechanism:
      "ساعة فاشن رجالية كرونوغراف من VORLAY — لوك تجاري مطلوب، مع تجربة COD واضحة.",
    eyebrow: "VORLAY Watches · كرونوغراف Pro · الدفع عند الاستلام",
    image: img("benyar", "benyar-01.jpg"),
    heroImageFit: "contain",
    carouselImageFit: "contain",
    images: [
      img("benyar", "benyar-01.jpg"),
      img("benyar", "benyar-02.jpg"),
      img("benyar", "benyar-03.jpg"),
      img("benyar", "benyar-04.jpg"),
      img("benyar", "benyar-05.jpg"),
      img("benyar", "benyar-06.jpg"),
    ],
    afterPainImage: img("benyar", "benyar-03.jpg"),
    storyImages: [img("benyar", "benyar-04.jpg"), img("benyar", "benyar-05.jpg")],
    crossSellIds: ["armani-chrono", "gshock"],
    offers: [
      {
        id: "benyar-1",
        productId: "benyar",
        quantity: 1,
        title: "ساعة واحدة",
        subtitle: "حضور قوي للرجال",
        badge: "موصى بها",
        priceMad: 379,
        compareAtPriceMad: 549,
        recommended: true,
      },
      {
        id: "benyar-2",
        productId: "benyar",
        quantity: 2,
        title: "ساعتين",
        subtitle: "هدية + الاستعمال الشخصي",
        badge: "أفضل قيمة",
        priceMad: 699,
        compareAtPriceMad: 758,
      },
    ],
  },
];

const upsellOffers: Offer[] = [
  {
    id: "upsell-gshock",
    productId: "gshock",
    quantity: 1,
    title: "زيد الساعة الرياضية",
    subtitle: "عرض خاص غير الآن قبل تأكيد الطلب",
    badge: "خصم خاص",
    priceMad: 249,
    compareAtPriceMad: 279,
    upsellOnly: true,
  },
  {
    id: "upsell-armani",
    productId: "armani-chrono",
    quantity: 1,
    title: "زيد الكرونوغراف الأنيق",
    subtitle: "عرض خاص غير الآن قبل تأكيد الطلب",
    badge: "خصم خاص",
    priceMad: 319,
    compareAtPriceMad: 349,
    upsellOnly: true,
  },
];

export const watchesCatalog: NicheCatalog = { products, upsellOffers };
